application: cssi-avalon
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- remote_api: on

handlers:
- url: /favicon\.jpg
  static_files: favicon.jpg
  upload: favicon\.jpg

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest